### ISSUE TITLE
Terraform crash :  rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by hobovirtual** [vmware-archive/terraform-provider-vra7#59] opened 2020-04-15 19:00 UTC
**vRA 7.x version**
vRealize Automation 7.6

**Terraform version**
v0.12.24

**terraform-provider-vra7 plugin version**
The terraform-provider-vra7 plugin version 1.0.0

**Describe the bug**
Issue with latest provider, when deploying any blueprint, at the end, terraform crash with the following error

rpc error: code = Unavailable desc = transport is closing

Since terraform crash the tfstate is not saved and we can no longer manage this deployment, haven't test the import functionality yet, but nonetheless, this shouldn't be required

**To Reproduce**
1. maint.tf content

```
provider "vra7" {
    username = var.vra_username
    password = var.vra_password
    tenant = var.vra_tenant
    host = var.vra_host
    insecure = true
}

resource "vra7_deployment" "deployment" {
  businessgroup_name = "dev"
  catalog_item_name = "dev vm"              
  reasons = "provide a reason"
  description = "provide a description"
  lease_days = 2

  resource_configuration {
    component_name = "vm1"
    cluster = 1

    //Please Provide the following information for the bootstrap node component
    configuration = {
      "custom.midname" = "BASE"
    }
  } 
}
```

2. Terraform command
terraform apply

3. Error
rpc error: code = Unavailable desc = transport is closing

**Expected behavior**
complete successfully

**Logs**
[crash.log](https://github.com/terraform-providers/terraform-provider-vra7/files/4483213/crash.log)

[vra-terraform.log](https://github.com/terraform-providers/terraform-provider-vra7/files/4483220/vra-terraform.log)

**Desktop (please complete the following information):**
 - OS: Windows 2016 and CentOS 7

**Comment by marratj** [comment] 2020-04-20 08:56
We have the same problem and found the underlying issue, we believe:

The provider expects "Scale Out" to be enabled in the Blueprint and is hardcoded to read the `_cluster` value from that:

```
			// the cluster value is fetched from scale out action template as the resourceViews API does not return that information
			deploymentResourceActions, _ := vraClient.GetResourceActions(parentResourceID)
			deploymentActionsMap := GetActionNameIDMap(deploymentResourceActions)
			scaleOutActionID := deploymentActionsMap["Scale Out"]
			resourceActionTemplate, _ := vraClient.GetResourceActionTemplate(parentResourceID, scaleOutActionID)
			actionTemplateResourceDataMap := GetActionTemplateDataByComponent(resourceActionTemplate.Data, componentName)
			rDataMap := actionTemplateResourceDataMap["data"].(map[string]interface{})
			var cluster int = int(rDataMap["_cluster"].(float64))
			resourceConfigStruct.Cluster = cluster
			// end
```

However, when a Blueprint has no scale out enabled, the `data` field in the API response is empty, causing the provider to crash with:

```
2020-04-17T17:02:36.163+0200 [DEBUG] plugin.terraform-provider-vra7_v1.0.0_x4: panic: interface conversion: interface {} is nil, not map[string]interface {}
2020-04-17T17:02:36.163+0200 [DEBUG] plugin.terraform-provider-vra7_v1.0.0_x4: 
2020-04-17T17:02:36.163+0200 [DEBUG] plugin.terraform-provider-vra7_v1.0.0_x4: goroutine 13 [running]:
2020-04-17T17:02:36.163+0200 [DEBUG] plugin.terraform-provider-vra7_v1.0.0_x4: github.com/terraform-providers/terraform-provider-vra7/vra7.resourceVra7DeploymentRead(0xc0002e2bd0, 0x1c2d5e0, 0xc0000427e0, 0x41, 0xc000268220)
2020-04-17T17:02:36.163+0200 [DEBUG] plugin.terraform-provider-vra7_v1.0.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vra7/vra7/resource_vra7_deployment.go:443 +0x1e0d
```

So there needs to be a check if the data field is even set or not.

**Comment by Prativa20** [comment] 2020-04-20 19:19
@hobovirtual @marratj The issue is fixed now.

**Closed as completed by Prativa20** 2020-04-20 19:19 UTC

**Comment by marratj** [comment] 2020-04-20 19:24
Thanks for your support. I tested your commit today already and can confirm it's working fine :)
