### ISSUE TITLE
Terraform apply returns empty ip address

### ISSUE THREAD

**Issue by diogoferreirasky** [vmware-archive/terraform-provider-vra7#27] opened 2019-08-16 13:27 UTC
**vRA 7.x version**
7.6.0
**Terraform version**
0.12.6
**terraform-provider-vra7 plugin version**
0.4

**Describe the bug**
Cannot output the IP Address. IP Address is still empty after deploying the VM.

**To Reproduce**
1. Terraform config file

```
resource "vra7_deployment" "vm" {
count = 1
catalog_item_name = "${var.catalog_name}"
catalog_item_id = "${var.catalog_id}"
description  = "${var.description}"
deployment_configuration = {
  _leaseDays = 6
}
resource_configuration = {
  "Machine.description" = "${var.description}"
  "Machine.cpu" = 1
  "Machine.memory" = 1024
.... (neccessary network configuration and others...) ......
  "Machine.ip_address" = ""
  "Machine.name"       = ""
  }
} 
```

2. Terraform command
terraform apply

3. Error
If you output the ip address, you will be able to see that no ip address is returned.
IP Address is still empty 
"Machine.ip_address" = ""

**Expected behavior**
IP Address variable should have a value after deploying the VM.
"Machine.ip_address" = "10.0.0.1"

**Logs**
There is no reference to ip address in the logs.

**Desktop:**
 - OS: Windows/Red Hat.

**Additional context**
Machine.name appears with the correct hostname.

**Comment by hobovirtual** [comment] 2019-08-16 16:26
Looks like a duplicate of issue #16?

**Comment by Prativa20** [comment] 2020-04-08 19:00
Duplicate of #16 Closing this

**Closed as completed by Prativa20** 2020-04-08 19:00 UTC
