### ISSUE TITLE
ERROR: "resource_configuration" is not expected here.

### ISSUE THREAD

**Issue by BalajiTechs** [vmware-archive/terraform-provider-vra7#67] opened 2020-05-01 03:13 UTC
**vRA 7.6.x version**
Version: 7.6.0 (Build: 13027133)
**Terraform version**
Terraform v0.12.24
**terraform-provider-vra7 plugin version**
provider.vra7 v1.0.1

**Describe the bug**
I want to set hostname of the machine i want to create. Here is my config file

```
provider "vra7" {
  username = "${var.username}"
  password = "${var.password}"
  tenant   = "${var.tenant}"
  host     = "${var.host}"
}

resource "vra7_deployment" "machine" {
  count             = 1
  catalog_item_name = "CentOS 7.0 x64"

  resource_configuration = {
    "Linux.cpu" = "2"
  }
}
```

when running command `terraform plan`, it throws below error

```
bash-4.2$ terraform plan

Error: Unsupported argument

  on main.tf line 13, in resource "vra7_deployment" "machine":
  13:   resource_configuration = {

An argument named "resource_configuration" is not expected here. Did you mean
to define a block of type "resource_configuration"?

````

**To Reproduce**
1. Terraform config file 
2. Terraform command
3. Error

**Expected behavior**
`terraform plan` command should not throw any error for 'resource_configuration' block.

**Screenshots**

**Logs**
Attach logs to help debug the issue
1. Attach vra-terraform.log
2. Attach Terraform console log (Enable terraform logs following the steps mentioned in https://www.terraform.io/docs/configuration/environment-variables.html)
3. crash.log(if any)

**Desktop (please complete the following information):**
 - OS: CentOS Linux 7

**Additional context**

**Comment by hobovirtual** [comment] 2020-05-01 12:13
Hi @BalajiTechs 

Version 1.x of the provider requires a new format for resource_configuration which you can see in the [example](https://github.com/terraform-providers/terraform-provider-vra7/blob/master/example/simple/main.tf)

From what i can see in the example above, your blueprint component is named Linux so your resource_configuration should look something like this

```
resource "vra7_deployment" "deployment" {
  catalog_item_name = "CentOS 7.0 x64"              
  reasons = "provide a reason"
  description = "provide a description"

  resource_configuration {
    component_name = "Linux"

    configuration = {
      cpu = 2
     //if you want to set hostname in your terraform manifest
     hostname = "myvmisawesome" 
    }
  } 
}
```

Hope this can help you move forward!!!

**Comment by BalajiTechs** [comment] 2020-05-02 13:59
Thanks @hobovirtual . 
Using above configuration doesn't throw the error mentioned in the issue. But at later stage it complains about the component_name = "Linux". How do i determine component_name  for my blueprint?

**Comment by hobovirtual** [comment] 2020-05-04 12:21
Hi @BalajiTechs 

There's many ways to see this information, i think the simplest is either via the blueprint design form (if you have access)

![image](https://user-images.githubusercontent.com/20516722/80964829-8792f500-8ddf-11ea-9a37-e3175f73e288.png)

or when you make a request in the portal

![image](https://user-images.githubusercontent.com/20516722/80964900-a6918700-8ddf-11ea-932c-87943221977b.png)

Other option is to get the request template via API following this [documentation](https://docs.vmware.com/en/vRealize-Automation/7.3/com.vmware.vra.programming.doc/GUID-C353A9E9-B2B6-43D0-89A5-B59B11522AC8.html)

**Comment by Prativa20** [comment] 2020-09-11 06:43
Hi @BalajiTechs 

Hope you could figure out how to get the component name. Closing this issue as this is not a bug.

Thanks,
Prativa

**Closed as completed by Prativa20** 2020-09-11 06:43 UTC
